### ISSUE TITLE
Update software on laptops

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2020#1]
We need to decide which laptops to update.  We probably don't want/need to maintain all 16 of them.  Need to coordinate with design and possibly other subteams.

**Comment by scottbot95** [comment]
We have created a spreadsheet to track the status of the upgrades https://docs.google.com/spreadsheets/d/1SLnilfFsDzrK6mhdi_6S1ij4WlGxTMXAj8marWEwIl4/edit#gid=0
