### ISSUE TITLE
USB Logging

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2020#10]
Port the USBLogging class from the frc1388-2019 project.
Consider updating the class to conform to best practices (e.g. design patterns being promoted by WPIlib this year).

**Comment by Bennnnnnnnnn** [comment]
Already done :)

**Comment by jtechau** [comment]
The code should be reviewed to see if any upgrades are appropriate, or if any unneeded functionality should be removed.
