### ISSUE TITLE
Install/Update Driver Laptops for Competition

### ISSUE THREAD

**Issue by Josiah-V** [AGHSEagleRobotics/frc1388-2020#30]
We need to decide which laptops will be used for Driver/Operator laptops, and then install and update the software needed for them to function. Most, if not all, of what we need is in the wiki.

**Comment by jtechau** [comment]
There are two HP laptops designated for driver stations.  As of today, they're located in the PR cabinet.  We need to:
- Update the software
- Label the laptops (e.g. label maker) to clearly identify them as Driver Station 1 and 2, and team number
- Collect two game controllers to be designated as competition controllers
- Test the laptops with a robot
- Put one of the laptops in the Pelican case, along with game controllers and a power adapter
- Get a laptop case to be used for the other driver station laptop, power adapter, and a spare game controller

**Comment by jtechau** [comment]
Two laptops have had software updated:
HP17 is now Driver Station 1
HP18 is now Driver Station 2
